language: ruby
script: "bundle exec rake test"
notifications:
  email:
    recipients:
      - engineering@internal.site5.com
    on_success: never
    on_failure: always
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
